name: Deploy to EC2 Docker

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::515421558980:role/GitHubActionsRole
        audience: sts.amazonaws.com
        role-session-name: GitHubActionsSession
    
    - name: Test AWS
      run: aws sts get-caller-identity
    
    - name: Login to ECR
      env:
        ECR_REGISTRY: 515421558980.dkr.ecr.us-east-1.amazonaws.com
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY
    
    - name: Build & Push ECR
      env:
        ECR_REGISTRY: 515421558980.dkr.ecr.us-east-1.amazonaws.com
      run: |
        docker build -t happy-newyear .
        docker tag happy-newyear:latest $ECR_REGISTRY/happy-newyear-app:latest
        docker push $ECR_REGISTRY/happy-newyear-app:latest
    
    - name: Deploy to EC2
  env:
    ECR_REGISTRY: 515421558980.dkr.ecr.us-east-1.amazonaws.com
  run: |
    aws ssm start-session --target i-03a340bbd050279ba \
      --document-name AWS-StartSSHSession \
      --parameters '{"portNumber":["22"]}' \
      --region us-east-1 << 'EOF'
    sudo yum install -y docker
    sudo systemctl enable --now docker
    aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin $ECR_REGISTRY
    sudo docker rm -f newyear-app || true
    sudo docker run -d --name newyear-app -p 80:80 $ECR_REGISTRY/happy-newyear-app:latest
    sudo systemctl stop httpd || true
    exit
    EOF

